'use client'
/* eslint-disable react-hooks/set-state-in-effect */

import { useCallback, useEffect, useState } from 'react'
import { ClipboardList, Eye, Loader2, MessageSquare, Plus, Wrench } from 'lucide-react'

interface LogEntry { id:string; action:string; summary:string|null; details:unknown; severity:string; created_at:string }
interface Room { id:string; room_number:string; room_type:string; status:string }
const defaults={action:'observation',details:'',title:'',roomId:'',location:'Resort property',category:'other',priority:'medium'}

export default function ActivityLogPage(){const[logs,setLogs]=useState<LogEntry[]>([]);const[rooms,setRooms]=useState<Room[]>([]);const[loading,setLoading]=useState(true);const[showForm,setShowForm]=useState(false);const[form,setForm]=useState(defaults);const[submitting,setSubmitting]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('')
const load=useCallback(async()=>{setLoading(true);const response=await fetch('/api/staff/activity',{cache:'no-store'});const data=await response.json();if(!response.ok)setError(data.error||'Unable to load activity.');else{setLogs(data.logs);setRooms(data.rooms);setError('')}setLoading(false)},[]);useEffect(()=>{void load()},[load])
const types=[{value:'observation',label:'General Observation',icon:Eye},{value:'maintenance',label:'Maintenance Issue',icon:Wrench},{value:'note',label:'Guest Note',icon:MessageSquare}]
async function submit(event:React.FormEvent){event.preventDefault();setSubmitting(true);setError('');setMessage('');const payload=form.action==='maintenance'?{action:'maintenance',title:form.title,details:form.details,roomId:form.roomId||null,location:form.location,category:form.category,priority:form.priority}:{action:form.action,details:form.details};const response=await fetch('/api/staff/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)setError(data.error||'Unable to submit report.');else{setMessage(data.message);setForm(defaults);setShowForm(false);await load()}setSubmitting(false)}
return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Activity & Issue Reporting</h1><p className="mt-1 text-sm text-gray-500">Record observations and send maintenance issues directly to the manager work-order queue.</p></div><button onClick={()=>setShowForm(!showForm)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#0A3D62] px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Add report</button></div>
{message&&<div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-700">{message}</div>}{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
{showForm&&<form onSubmit={submit} className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-bold text-gray-900">New report</h2><div className="mt-4 flex flex-wrap gap-2">{types.map(type=><button key={type.value} type="button" onClick={()=>setForm({...form,action:type.value})} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold ${form.action===type.value?'border-[#0A3D62] bg-[#0A3D62] text-white':'border-gray-300 text-gray-600'}`}><type.icon className="h-4 w-4"/>{type.label}</button>)}</div>
<div className="mt-5 grid gap-4 sm:grid-cols-2">{form.action==='maintenance'&&<><label className="sm:col-span-2 text-sm font-medium text-gray-700">Issue title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="input" placeholder="For example: Air conditioner not cooling"/></label><label className="text-sm font-medium text-gray-700">Room or area<select value={form.roomId} onChange={e=>{const room=rooms.find(item=>item.id===e.target.value);setForm({...form,roomId:e.target.value,location:room?`Room ${room.room_number}`:'Resort property'})}} className="input"><option value="">General resort area</option>{rooms.map(room=><option key={room.id} value={room.id}>Room {room.room_number} — {room.room_type} ({room.status})</option>)}</select></label><label className="text-sm font-medium text-gray-700">Location<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="input" placeholder="Pool area, restaurant, Room 203…"/></label><label className="text-sm font-medium text-gray-700">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="input">{['electrical','plumbing','air_conditioning','housekeeping','furniture','safety','it','other'].map(value=><option key={value} value={value}>{value.replace(/_/g,' ')}</option>)}</select></label><label className="text-sm font-medium text-gray-700">Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="input"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></>}
<label className="sm:col-span-2 text-sm font-medium text-gray-700">{form.action==='maintenance'?'Issue description':'Details'}<textarea required minLength={form.action==='maintenance'?5:3} rows={4} value={form.details} onChange={e=>setForm({...form,details:e.target.value})} className="input" placeholder={form.action==='maintenance'?'Describe the fault, impact, and any immediate safety concern.':'Enter the observation or guest note.'}/></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowForm(false)} className="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold text-gray-600">Cancel</button><button disabled={submitting} className="inline-flex items-center gap-2 rounded-lg bg-[#F97316] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{submitting&&<Loader2 className="h-4 w-4 animate-spin"/>}{form.action==='maintenance'?'Create work order':'Save report'}</button></div></form>}
<section className="overflow-hidden rounded-xl border bg-white"><div className="border-b px-5 py-4"><h2 className="font-bold text-gray-900">Recent staff reports</h2></div>{loading?<div className="flex justify-center p-12"><Loader2 className="h-6 w-6 animate-spin"/></div>:<div className="divide-y">{logs.map(log=>{const Icon=log.action.includes('maintenance')?Wrench:log.action==='note'?MessageSquare:ClipboardList;return <article key={log.id} className="flex gap-3 p-4"><div className={`rounded-lg p-2 ${log.severity==='critical'?'bg-red-100 text-red-700':log.action.includes('maintenance')?'bg-orange-100 text-orange-700':'bg-blue-100 text-blue-700'}`}><Icon className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between"><p className="font-semibold text-gray-900">{log.summary||log.action.replace(/_/g,' ')}</p><span className="text-xs text-gray-400">{new Date(log.created_at).toLocaleString('en-NG')}</span></div><p className="mt-1 text-sm text-gray-600">{detailText(log.details)}</p></div></article>})}{!logs.length&&<div className="p-10 text-center text-gray-400">No reports yet.</div>}</div>}</section></div>}

function detailText(details:unknown){if(typeof details==='string')return details;if(details&&typeof details==='object'){const value=details as Record<string,unknown>;return String(value.note||value.description||'Structured activity recorded.')}return ''}
